# Generated by Django 2.1.1 on 2018-09-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre_res', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='restaurantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_res', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
