# Generated by Django 2.1.1 on 2018-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0004_auto_20181007_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
