# Generated by Django 2.1.1 on 2018-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0005_auto_20181007_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
