# Generated by Django 2.1.1 on 2018-10-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesApp', '0007_auto_20181015_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=120)),
                ('platillo', models.CharField(max_length=120)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('domicilio', models.CharField(max_length=120)),
                ('observacion', models.TextField()),
                ('nombre_res', models.CharField(max_length=120)),
            ],
        ),
    ]
