# Generated by Django 2.1.1 on 2018-10-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0002_auto_20181014_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
